[project]
name = "better-git-diff"
version = "0.1.0"
description = "A library for extracting function-level diffs from Python files in git repositories"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.40",
]

[tool.uv]
dev-dependencies = ["pytest>=7.0.0"]